# -*- coding: utf-8 -*-
"""Deployment_VGG16_Streamlit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11wvchbd8gARV98YSsNkjnAFYl1Kxwn37
"""

#%%streamlit
import streamlit as st # type: ignore
import tensorflow as tf # type: ignore
import numpy as np # type: ignore
#streamlit run your_app_script.py

#from google.colab import drive
#drive.mount('/content/drive/')

# Load the trained model
model_deployment = tf.keras.models.load_model("C:/Users/suchi/Downloads/Transfer Learning/model_deployment.h5")

# Define the Streamlit app
def main():
    st.title("Image Classifier")
    st.write("Upload an image to classify Emotion")

    # File uploader component
    uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "jpeg", "png"])

    if uploaded_file is not None:
        # Display the uploaded image
        st.image(uploaded_file, caption="Uploaded Image", use_column_width=True)

        # Preprocess the image
        img = tf.image.decode_image(uploaded_file.read(), channels=3)
        img = tf.image.resize(img, (224, 224))
        img = img / 255.0  # Normalize the image

        # Make predictions
        predictions = model_deployment.predict(tf.expand_dims(img, axis=0))

        # Display the predictions
        st.subheader("Predictions")
        labels = ["Happy", "Sad", "Surprise", "Neutral"]
        for label, prob in zip(labels, predictions[0]):
            st.write(f"{label}: {prob:.2f}")

# Run the Streamlit app
if __name__ == "__main__":
    main()